/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package exa;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author edgva
 */
public class MainPSNusers extends javax.swing.JFrame {

    /**
     * Creates new form MainPSNusers
     */
    public MainPSNusers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonPlayerInfo = new javax.swing.JButton();
        botonAgregarUser = new javax.swing.JButton();
        BotonDesactivarUsuario = new javax.swing.JButton();
        botonAgregarTrofeo = new javax.swing.JButton();
        BotonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonPlayerInfo.setText("PlayerInfo");
        botonPlayerInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPlayerInfoActionPerformed(evt);
            }
        });

        botonAgregarUser.setText("Agregar Usuario");
        botonAgregarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarUserActionPerformed(evt);
            }
        });

        BotonDesactivarUsuario.setText("Desactivar Usuario");
        BotonDesactivarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDesactivarUsuarioActionPerformed(evt);
            }
        });

        botonAgregarTrofeo.setText("Agregar Trofeo");
        botonAgregarTrofeo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarTrofeoActionPerformed(evt);
            }
        });

        BotonSalir.setText("Salir ");
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonAgregarTrofeo)
                    .addComponent(botonPlayerInfo)
                    .addComponent(BotonSalir)
                    .addComponent(BotonDesactivarUsuario)
                    .addComponent(botonAgregarUser))
                .addContainerGap(255, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(botonAgregarUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonDesactivarUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonAgregarTrofeo)
                .addGap(18, 18, 18)
                .addComponent(botonPlayerInfo)
                .addGap(18, 18, 18)
                .addComponent(BotonSalir)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonPlayerInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPlayerInfoActionPerformed
        // TODO add your handling code here:
  
    }//GEN-LAST:event_botonPlayerInfoActionPerformed

    private void botonAgregarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarUserActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_botonAgregarUserActionPerformed

    private void BotonDesactivarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDesactivarUsuarioActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_BotonDesactivarUsuarioActionPerformed

    private void botonAgregarTrofeoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarTrofeoActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_botonAgregarTrofeoActionPerformed

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BotonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPSNusers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPSNusers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPSNusers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPSNusers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPSNusers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonDesactivarUsuario;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JButton botonAgregarTrofeo;
    private javax.swing.JButton botonAgregarUser;
    private javax.swing.JButton botonPlayerInfo;
    // End of variables declaration//GEN-END:variables
}
